version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: springblog

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8090
